### ISSUE TITLE
Doesn't handle UTF-8 text well

### ISSUE THREAD

**Issue by kseistrup** [ipfs/py-ipfs-api#36]
The API seems to mangle UTF-8 encoded text in a way as if it had received ISO-8859-1 encoded bytes from IPFS and then transformed each byte to a multibyte UTF-8 sequence.

First we create a file with UTF-8 contents:
```sh
$ echo Frække frølår | ipfs add
added QmciJtwy4qy7nqzW4pDxhJbUhkpTjKiH5AAmkFLAWWfnmT QmciJtwy4qy7nqzW4pDxhJbUhkpTjKiH5AAmkFLAWWfnmT
$ ipfs cat QmciJtwy4qy7nqzW4pDxhJbUhkpTjKiH5AAmkFLAWWfnmT
Frække frølår
$
```
Next, let's try and fetch the same content from Python:
```py
>>> import ipfsApi
>>> api = ipfsApi.Client('127.0.0.1', 5001)
>>> res = api.cat('QmciJtwy4qy7nqzW4pDxhJbUhkpTjKiH5AAmkFLAWWfnmT').rstrip('\n')
>>> print(res)
FrÃ¦kke frÃ¸lÃ¥r
>>> print(res.encode('iso-8859-1').decode('utf-8'))
Frække frølår
>>>
```

**Comment by candeira** [comment]
Reproduced under Python 3.5. The text comes out fine under Python2.7, so it's clear that the problem is a Python3 compatibility issue.

```
>>> res = api.cat('QmciJtwy4qy7nqzW4pDxhJbUhkpTjKiH5AAmkFLAWWfnmT').rstrip('\n')
>>> res
u'Fr\xe6kke fr\xf8l\xe5r'
>>> print res
Frække frølår
>>> res.encode('iso-8859-1').decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe6 in position 2: invalid continuation byte
>>> print res.encode('utf-8').decode('utf-8')
Frække frølår
```

**Comment by kseistrup** [comment]
I'm sorry that I didn't mention the Python version earlier.

There's nothing wrong with the locale settings in my terminal:
```sh
$ locale | grep -v '"'
LANG=en_DK.UTF-8
LC_ALL=en_DK.UTF-8
$
```
And usually `python-requests` handles UTF-8 (and other charsets) just fine:
```py
>>> import sys
>>> import os
>>> print(sys.version)
3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0]
>>> print(os.environ.get('LANG'))
en_DK.UTF-8
>>> print(os.environ.get('LC_ALL'))
en_DK.UTF-8
>>> import requests
>>> res = requests.get('https://enotty.dk/test/utf8.txt')
>>> print(res.text.rstrip('\n'))
Frække frølår
>>> print(res.headers['Content-Type'])
text/plain; charset=utf-8
>>>
```
However, `go-ipfs` doesn't indicate a charset in its response:
```sh
$ curl -Is 'http://127.0.0.1:5001/api/v0/cat?arg=QmciJtwy4qy7nqzW4pDxhJbUhkpTjKiH5AAmkFLAWWfnmT&stream-channels=true&encoding=json' | grep Content-Type
Content-Type: text/plain
$
```
So perhaps `python-requests` can be forgiven for not knowing the encoding of the data it receives from `go-ipfs`?

**Comment by kseistrup** [comment]
Btw, this is `ipfs version 0.4.0-dev`.

**Comment by kseistrup** [comment]
[RFC 2616](https://tools.ietf.org/html/rfc2616#section-3.7.1) says:
> When no explicit charset parameter is provided by the sender, media subtypes of the "text" type are defined to have a default charset value of "ISO-8859-1" when received via HTTP. Data in character sets other than "ISO-8859-1" or its subsets MUST be labeled with an appropriate charset value.

So it seems requests' behaviour is correct. Perhaps I should submit an issue to the `go-ipfs` project.

**Comment by candeira** [comment]
Tests forthcoming. I found that the tests in `test/functional/tests.py` weren't being run by tox, and when I ran them I found that the behaviour of `api.add` doesn't pass tests on my version of ipfs, which was outdated. So it's all taking a while as I download, recompile, etc.

**Comment by kseistrup** [comment]
In my opinion `requests`, and by association `py-ipfs-api`, does the right thing. The `go-ipfs` API, according to RFC 2616, **must** set a `charset` specification, but doesn't.

**Comment by kseistrup** [comment]
It seems to be a wellknown, if still open, bug in the `go-ipfs` API: ipfs/go-ipfs#1817

**Comment by candeira** [comment]
It's a regression in 0.4. My tests for unicode passed in 0.3.8, fail in 0.4.

I'm going to make a pull request with the tests, call it a day.

Well, at least I got to install 0.4.0-dev...

**Comment by kseistrup** [comment]
Well done. Thanks!

**Comment by candeira** [comment]
Noworries, it's been fun!

**Comment by candeira** [comment]
Also other, existing tests fail now too under 0.4.0-dev. Don't know whether it's because the API has changed or because of other bugs.

I guess it will have to wait till tomorrow to fix it all and send it packing githubwards.

**Comment by ingokeck** [comment]
Speaking of failing tests, the tests in test/functional/tests.py fail as well. I was not able to dive into deep, but the assertEqual fails because the api call gives back an unicode string instead of lists/dictionaries. Getting of python objects (api.get_pyobj(...)) also fails with an error that hints an encoding issue. So I guess the issues are connected. (Macosx 10.10.5, python 3.4, ipfs 0.3.10, py-ipfs-api cloned yesterday).

**Comment by whereswaldon** [comment]
@kseistrup @ingokeck @candeira Can anyone confirm whether this has been resolved in the current version of py-ipfs-api? We've fixed the functional tests and are now compatible with the latest release of go-ipfs, but I don't know if they ever resolved the encoding problem.

**Comment by kseistrup** [comment]
@whereswaldon I just installed py-ipfs-api on Python 3.5.2 and reran the python code shown in my original post. Same result as then.

**Comment by whereswaldon** [comment]
@kseistrup Okay, thank you. I'll look into it.

**Comment by alexander255** [comment]
This should be fixed by #65.

**Comment by kseistrup** [comment]
I just installed from git and I still see the same issue.
```py
>>> res
'FrÃ¦kke frÃ¸lÃ¥r'
```
Did I miss something?

**Comment by alexander255** [comment]
The result of `cat` should now be a binary string (since an IPFS object may hold any kind of data, not just UTF-8 text). Could you please document again the exact commands you've used?

Working example:

```py
>>> import ipfsapi
>>> c = ipfsapi.Client()
>>> c.cat('QmciJtwy4qy7nqzW4pDxhJbUhkpTjKiH5AAmkFLAWWfnmT')
b'Fr\xc3\xa6kke fr\xc3\xb8l\xc3\xa5r\n'
```

Also note that the Python package has been renamed from `ipfsApi` to `ipfsapi`, so you might be using the stale PIP package instead.

**Comment by kseistrup** [comment]
@alexander255 I installed directly from github today (`sudo pip install 'git+https://github.com/ipfs/py-ipfs-api.git'`) and used the exact same sequence as when I reported this issue. I was unaware that the API has changed — mea culpa. When I use your example I do indeed get a valid bytes buffer back from the API call. I'm sorry for the confusion.
